image: node:boron
services:
  - redis

before_script:
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

after_script:
  - rm secrets

stages:
  - build
  - test
  - deploy

variables:
  - "NODE_ENV": "production"

job1:
  stage: build
  script:
    - yarn
  only:
    - master
  tags:
    - docker
