build: .

stages:
  - test
  - build
  - deploy

before_script:
  - yarn

cache:
  paths:
    - node_modules

variables:
  S3_FOLDER: "ci-app"

test_unit:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build

deploy_to_production:
  stage: deploy
  script:
    - apt-get update
    - apt-get -y install python-pip
    - pip install awscli
    - npm run generate
    - aws s3 cp ./dist s3://$S3_BUCKET_NAME/$S3_FOLDER --recursive
  environment:
    name: production
    url: https://s3.amazonaws.com/$S3_BUCKET_NAME/$S3_FOLDER/index.html
  only:
    - master

pages:
  stage: deploy
  script:
    - npm run generate
    - mkdir -p ./public
    - cp -R ./dist/* ./public
  environment:
      name: staging
  artifacts:
    paths:
    - public
  except:
    - master