image: node:alpine

stages:
  - test
  - build
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules

test_unit:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build

deploy_to_production:
  stage: deploy
  script:
    - mkdir -p /aws
    - apk -Uuv add py-pip
    - pip install awscli
    - npm run generate
    - aws s3 cp ./dist s3://$S3_BUCKET_NAME/$S3_BUCKET_FOLDER --recursive
  environment:
    name: production
    url: https://s3.amazonaws.com/$S3_BUCKET_NAME/$S3_FOLDER/index.html
  only:
    - master

pages:
  stage: deploy
  script:
    - npm run generate
    - mkdir -p ./public
    - cp -R ./dist/* ./public
  environment:
      name: staging
      url: http://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME/
  artifacts:
    paths:
    - public
  except:
    - master