version: '2'
services:
  app:
    build: .
    ports:
      - "3000" # dynamically set host port for scale
    environment:
      - NODE_ENV=production

  haproxy:
    image: haproxy:alpine
    links:
      - app
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro